### ISSUE TITLE
Clarification regarding Aggregate Root

### ISSUE THREAD

**Issue by ffazil** [avthart/spring-boot-axon-sample#1]
Hi Albert. 

I went through the code and saw it working. Feels great to see CQRS, Websockets and boot work together. However am not that familiar with Axon. Not sure, if you are the right person to ask. 

The Aggregate root `Task` has only 2 attributes
- id
- completed

My doubts are 
- Shouldn't the aggregate root contain the attribute name? 
- Also the `command handlers` should mutate the state in `Aggregate root` and publish the current state of the object?

**Comment by avthart** [comment]
Hi @ffazil,

The aggregate root only contains data which is needed to handle state changes. 
e.g. the name property is currently not needed to handle/process the Task commands.

The aggregate root is publishing the events which corresponds to the intent (command) of the user.

Some links about CQRS which can help you.
http://culttt.com/2015/01/14/command-query-responsibility-segregation-cqrs/
http://www.udidahan.com/2009/12/09/clarified-cqrs/
https://msdn.microsoft.com/en-us/library/dn568103.aspx

Hope this explanation and links can help you further.

**Comment by ffazil** [comment]
Hi @avthart 

Thanks for the explanation and the links.
