### ISSUE TITLE
About store event source

### ISSUE THREAD

**Issue by RobertoHuang** [avthart/spring-boot-axon-sample#6]
Hi
      in your code，did not find the logic of when to store the event source，Can you explain why the event source is stored when the task is created? Thanks!

**Comment by avthart** [comment]
Hi @RobertoHuang, this example is using the Axon Framework. If JPA is available, an Event Store with a JPA Event Storage Engine is used by default. This allow storage of Aggregates using Event Sourcing without any explicit configuration.

You can read more here:
https://docs.axonframework.org/part-iii-infrastructure-components/spring-boot-autoconfiguration
